#!/usr/bin/env python3
'''
# Team ID:          <  eYRC#1710 >
# Theme:            < Krishi Drone >
# Author List:      < Ameya Degaonkar,Sarthak Benodkar,Aditya Dengale,Pranav Rokade>
# Filename:         < pico_server >
# Functions:        < __init__, disarm, arm, whycon_callback, altitude_set_pid, pitch_set_pid, 
# roll_set_pid, odometry_callback, pid, execute_callback, is_drone_in_sphere, main >
# Global variables: < Kp_hover, Ki_hover, Kd_hover, Kp_travel, Ki_travel, Kd_travel, Kp, Ki, Kd, cmd, 
# prev_error, max_values, min_values, error, p_term, d_term, i_term, PID_out, dt, error_sum, filterted_curr_state, alpha, sample_time, time_inside_sphere, 
# max_time_inside_sphere, point_in_sphere_start_time, duration, first_waypoint_processed, yaw, xyz, curr_state, 
# desired_state, dtime, out_roll, out_pitch, out_throttle, roll_deg, pitch_deg, yaw_deg,self.alpha , self.d_term_filtered 
#  self.hover_gains,  self.travel_gains,self.hover_point,self.gain_switch_radius,self.d_alpha,self.d_term_filtered>'''


# This python file runs a ROS 2-node of name waypoint_server which implements an action server to navigate the Swift Pico Drone to the given waypoints.
# You can use either PID or LQR controller to navigate the drone to the given waypoints.


import time
import math
from tf_transformations import euler_from_quaternion

import rclpy
from rclpy.action import ActionServer
from rclpy.node import Node
from rclpy.callback_groups import ReentrantCallbackGroup
from rclpy.executors import MultiThreadedExecutor
from rclpy.action.server import ServerGoalHandle
import numpy as np
#import control specific libraries
#import the action
from waypoint_navigation.action import NavToWaypoint
#pico control specific libraries
from swift_msgs.msg import SwiftMsgs
from geometry_msgs.msg import PoseArray
from error_msg.msg import Error
from controller_msg.msg import PIDTune
from nav_msgs.msg import Odometry

class WayPointServer(Node):

    def __init__(self):
        '''
Purpose:
---
Initializes the waypoint server node, sets up publishers, subscribers, action server, and 
PID controller parameters for drone waypoint navigation.
Input Arguments:
---
None

Returns:
---
None

Example call:
---
waypoint_server = WayPointServer()
'''

        super().__init__('waypoint_server')

        self.pid_or_lqr_callback_group = ReentrantCallbackGroup()
        self.action_callback_group = ReentrantCallbackGroup()
        self.odometry_callback_group = ReentrantCallbackGroup()

        self.time_inside_sphere = 0
        self.max_time_inside_sphere = 0
        self.point_in_sphere_start_time = None
        self.duration = 0

        self.yaw = 0.0
        self.xyz = [0.0, 0.0, 0.0, 0.0]
        self.curr_state = [0.0, 0.0, 0.0]
        self.desired_state = [0.0, 0.0, 0.0]
        self.dtime = 0

        # Declaring a cmd of message type swift_msgs and initializing values
        self.cmd = SwiftMsgs()
        self.cmd.rc_roll = 1500
        self.cmd.rc_pitch = 1500
        self.cmd.rc_yaw = 1500
        self.cmd.rc_throttle = 1500

        self.Kp = [ 0.0, 0.0, 0.0] 
        self.Ki = [ 0.0, 0.0, 0.0] 
        self.Kd = [ 0.0, 0.0, 0.0]

        #Initiate or declare other variables here depending upon whether you are implementing PID or LQR controller.
        self.prev_error = [0.0, 0.0, 0.0]
        self.max_values = [2000, 2000, 2000]
        self.min_values = [1000, 1000, 1000]
        self.error = [0.0, 0.0, 0.0]
        self.p_term = [0.0, 0.0, 0.0]
        self.d_term = [0.0, 0.0, 0.0]
        self.i_term = [0.0, 0.0, 0.0]
        self.PID_out = [0.0, 0.0, 0.0]
        self.dt = [0.0, 0.0, 0.0]
        self.error_sum = [0.0, 0.0, 0.0]
        #variable for filter
        self.alpha = 0.9
        self.filtered_curr_state = [0.0,0.0,0.0]
        #gain scheduling 
        self.hover_gains = {
            'Kp': [0.0, 0.0, 40.0],
            'Ki': [0.0, 0.0, 1.0],
            'Kd': [0.0, 0.0, 40.0]
        }
        self.travel_gains = {
        'Kp': [-20.0, -25.0, 40.0],
        'Ki': [ -1.0, -1.0,  1.0],
        'Kd': [-20.0, -25.0, 40.0]
        }

        #hover_point decide which gain to pick
        self.hover_point = [-7.00, 0.00, 29.22]
        self.gain_switch_radius = 0.5 # meters

        #variable for d filter
        self.d_alpha = 0.95
        self.d_term_filtered = [0.0, 0.0, 0.0]

        self.sample_time = 0.03 #put the appropriate value according to your controller

        self.command_pub = self.create_publisher(SwiftMsgs, '/drone_command', 10)
        self.pos_error_pub = self.create_publisher(Error, '/position_error', 10)

        
        self.create_subscription(PoseArray, '/whycon/poses', self.whycon_callback, 1)
        #Add other sunscribers here
        self.create_subscription(PIDTune, "/throttle_pid", self.altitude_set_pid, 1)
        self.create_subscription(PIDTune, "/pitch_pid", self.pitch_set_pid, 1)
        self.create_subscription(PIDTune, "/roll_pid", self.roll_set_pid, 1)
        self.create_subscription(Odometry, '/rotors/odometry', self.odometry_callback, 10, callback_group=self.odometry_callback_group)

        #create an action server for the action 'NavToWaypoint'. Refer to Writing an action server and client (Python) in ROS 2 tutorials
        #action name should 'waypoint_navigation'.
        #include the action_callback_group in the action server. Refer to executors in ROS 2 concepts
        self.pico_server_ = ActionServer(
            self,
            NavToWaypoint,
            "waypoint_navigation",
            execute_callback=self.execute_callback,
            callback_group=self.action_callback_group)
        self.get_logger().info("Action server has been started.")
        
        self.arm()
        #define the function to be run inside the timer callback. This function will implement the PID or LQR algorithm
        self.timer = self.create_timer(self.sample_time, self.pid, callback_group=self.pid_or_lqr_callback_group)

    def disarm(self):
        '''
Purpose:
---
Sends command to disarm the drone for safety, setting all control channels to minimum values.
Input Arguments:
---
None

Returns:
---
None

Example call:
---
self.disarm()
'''

        self.cmd.rc_roll = 1000
        self.cmd.rc_yaw = 1000
        self.cmd.rc_pitch = 1000
        self.cmd.rc_throttle = 1000
        self.cmd.rc_aux4 = 1000
        self.command_pub.publish(self.cmd)


    def arm(self):
        '''
Purpose:
---
Arms the drone by sending control values to appropriate channels, preparing for flight and navigation.

Input Arguments:
---
None

Returns:
---
None

Example call:
---
self.arm()
'''

        self.disarm()
        self.cmd.rc_roll = 1500
        self.cmd.rc_yaw = 1500
        self.cmd.rc_pitch = 1500
        self.cmd.rc_throttle = 1500
        self.cmd.rc_aux4 = 2000
        self.command_pub.publish(self.cmd)


	# Whycon callback function
	# The function gets executed each time when /whycon node publishes /whycon/poses 
    def whycon_callback(self, msg):
        '''
Purpose:
---
Receives position data from the /whycon/poses 
topic and updates the drone's current state using a low-pass filter.

Input Arguments:
---
`msg` : [PoseArray]
    PoseArray message from /whycon/poses topic containing position data.

Returns:
---
None


Example call:
---
self.whycon_callback(msg)
'''


        if not msg.poses or len(msg.poses) == 0:
            self.get_logger().warn("No poses received")
            return

        else:
            #complete the function according to your controller as you did in task 1c.
            #filter
            raw_x = msg.poses[0].position.x 
            raw_y = msg.poses[0].position.y 
            raw_z = msg.poses[0].position.z 
            
            self.filtered_curr_state[0]=self.alpha * raw_x + (1 - self.alpha)* self.filtered_curr_state[0]
            self.filtered_curr_state[1]=self.alpha * raw_y + (1 - self.alpha)* self.filtered_curr_state[1]
            self.filtered_curr_state[2]=self.alpha * raw_z + (1 - self.alpha)* self.filtered_curr_state[2]

            self.curr_state[0] = self.filtered_curr_state[0]
            self.curr_state[1] = self.filtered_curr_state[1]
            self.curr_state[2] = self.filtered_curr_state[2]

        self.dtime = msg.header.stamp.sec

    # If you are using PID controller, then define callback function like altitide_set_pid to tune pitch, roll.
    #If you are using LQR controller, then define a functions which were given in the boiler plate code of task 1c and the ones which you have defined on yur own.
    def altitude_set_pid(self, alt):
        '''
Purpose:
---
Updates PID gains for altitude control using incoming PIDTune message.

Input Arguments:
---
`alt` : [PIDTune]
    PID tuning gains for altitude (throttle) control.

Returns:
---
None

Example call:
---
self.altitude_set_pid(alt)
'''

        self.Kp[2] = alt.kp * 0.03  # This is just for an example. You can change the ratio/fraction value accordingly
        self.Ki[2] = alt.ki * 0.008
        self.Kd[2] = alt.kd * 0.6

    def pitch_set_pid(self, alt):
        '''
Purpose:
---
Updates PID gains for pitch control using incoming PIDTune message.

Input Arguments:
---
`alt` : [PIDTune]
    PID tuning gains for pitch control.

Returns:
---

None

Example call:
---
self.pitch_set_pid(alt)
'''

        self.Kp[0] = alt.kp * 0.03  # This is just for an example. You can change the ratio/fraction value accordingly
        self.Ki[0] = alt.ki * 0.008
        self.Kd[0] = alt.kd * 0.6

    def roll_set_pid(self, alt):
        '''
Purpose:
---
Updates PID gains for roll control using incoming PIDTune message.

Input Arguments:
---
`alt` : [PIDTune]
    PID tuning gains for roll control.

Returns:
---
None

Example call:
---
self.roll_set_pid(alt)
'''

        self.Kp[1] = alt.kp * 0.03  # This is just for an example. You can change the ratio/fraction value accordingly
        self.Ki[1] = alt.ki * 0.008
        self.Kd[1] = alt.kd * 0.6

    def odometry_callback(self, msg):
        '''
Purpose:
---
Receives orientation data from the /rotors/odometry topic,
converts quaternion to Euler angles, and updates yaw, pitch, roll values.

Input Arguments:
---
`msg` : [Odometry]
    Odometry message containing drone orientation.

Returns:
---
None

Example call:
---
self.odometry_callback(msg)
'''

        orientation_q = msg.pose.pose.orientation
        orientation_list = [orientation_q.x, orientation_q.y, orientation_q.z, orientation_q.w]
        roll, pitch, yaw = euler_from_quaternion(orientation_list)

        self.roll_deg = math.degrees(roll)
        self.pitch_deg = math.degrees(pitch)
        self.yaw_deg = math.degrees(yaw)
        self.yaw = self.yaw_deg	

    #define the function to be run inside the timer callback. This function will implement the PID or LQR algorithm. 
    # This will be either 'pid' finction or 'controller' function as you can see in the boiler plate for PID or LQR for task 1c.
    def pid(self):
        '''
Purpose:
---
Calculates PID control output for roll, pitch, and throttle.
Publishes command signals and position errors for navigation correction.

Input Arguments:
---
None


Returns:
---
None

Example call:
---

self.pid()
''' 
        self.error[0] = self.curr_state[0] - self.desired_state[0]
        self.error[1] = self.curr_state[1] - self.desired_state[1]
        self.error[2] = self.curr_state[2] - self.desired_state[2]

        deadband = [0.4,0.4,0.25]
        for i in range(3):
            if abs(self.error[i]) < deadband[i]:
                self.error[i] = 0.0 

        for i in range(3):
            self.p_term[i] = self.Kp[i] * self.error[i] 
            
            #derivative        
            self.dt[i] = (self.error[i] - self.prev_error[i]) / self.sample_time
            self.d_term[i] = self.Kd[i] * self.dt[i]
            
            #first order low _pass filter
            self.d_term_filtered[i] = self.d_alpha * self.d_term_filtered[i] + (1.0 - self.d_alpha) * self.d_term[i]

            # integral calculation
            self.error_sum[i] += self.error[i] * self.sample_time
            self.i_term[i] = self.error_sum[i] * self.Ki[i]

            # use filtered derivative in final PID output
            self.PID_out[i] = self.p_term[i] + self.i_term[i] + self.d_term_filtered[i]
        
        self.out_roll = self.PID_out[1]
        self.out_pitch = self.PID_out[0]
        self.out_throttle = self.PID_out[2]

        self.cmd.rc_roll = 1500 + int(self.out_roll)
        self.cmd.rc_pitch = 1500 + int(self.out_pitch)
        self.cmd.rc_throttle = 1500 + int(self.out_throttle)

        self.cmd.rc_roll = max(self.min_values[1],min(self.cmd.rc_roll,self.max_values[1]))
        self.cmd.rc_pitch = max(self.min_values[0],min(self.cmd.rc_pitch,self.max_values[0]))
        self.cmd.rc_throttle = max(self.min_values[2],min(self.cmd.rc_throttle,self.max_values[2]))

        for i in range(3):
            self.prev_error[i] = self.error[i]

        #publishing the error
        self.command_pub.publish(self.cmd)
        msg = Error()
        msg.roll_error = self.error[1]    
        msg.pitch_error = self.error[0] 
        msg.throttle_error = self.error[2]  
        self.pos_error_pub.publish(msg)

    def execute_callback(self, goal_handle:ServerGoalHandle):
        '''
Purpose:
---
Handles incoming navigation goals from the action server, 
manages feedback about drone stabilization, and returns action results to client.

Input Arguments:
---
`goal_handle` : [ServerGoalHandle]
    Action server goal handle containing requested waypoint.

Returns:
---
`result` : [NavToWaypoint.Result]
    Result object describing stabilization time at waypoint.

Example call:
---
self.execute_callback(goal_handle)
'''

        self.get_logger().info('Executing goal...')
        self.desired_state[0] = goal_handle.request.waypoint.position.x
        self.desired_state[1] = goal_handle.request.waypoint.position.y
        self.desired_state[2] = goal_handle.request.waypoint.position.z

        self.get_logger().info(f'New Waypoint Set: {self.desired_state}')
        
        target = self.desired_state

        dist = math.sqrt(
            (target[0] - self.hover_point[0])**2 +
            (target[1] - self.hover_point[1])**2 +
            (target[2] - self.hover_point[2])**2
        )

        if dist <= self.gain_switch_radius:
            self.get_logger().info("Using HOVER gains")
            self.Kp = self.hover_gains['Kp'].copy()
            self.Ki = self.hover_gains['Ki'].copy()
            self.Kd = self.hover_gains['Kd'].copy()
        else:
            self.get_logger().info("Using TRAVEL gains")
            self.Kp = self.travel_gains['Kp'].copy()
            self.Ki = self.travel_gains['Ki'].copy()
            self.Kd = self.travel_gains['Kd'].copy()

        self.max_time_inside_sphere = 0
        self.point_in_sphere_start_time = None
        self.time_inside_sphere = 0
        self.duration = self.dtime 

        for i in range(3):
            self.error[i] = 0.0
            self.prev_error[i]=0.0
            self.error_sum[i]=0.0
            self.d_term_filtered[i]=0.0
            self.p_term[i]=0.0
            self.i_term[i]=0.0
            self.d_term[i]=0.0
            self.PID_out[i]=0.0
            
        stabilize_here = target[0] < -4.5

        #create a NavToWaypoint feedback object. Refer to Writing an action server and client (Python) in ROS 2 tutorials.
        feedback_msg = NavToWaypoint.Feedback()
        #--------The script given below checks whether you are hovering at each of the waypoints(goals) for max of 3s---------#
        # This will help you to analyse the drone behaviour and help you to tune the PID better.
        if stabilize_here:
            while True:
		#current whycon poses
                feedback_msg.current_waypoint.pose.position.x = round(self.curr_state[0],2)
                feedback_msg.current_waypoint.pose.position.y = round(self.curr_state[1],2)
                feedback_msg.current_waypoint.pose.position.z = round(self.curr_state[2],2)
                feedback_msg.current_waypoint.header.stamp.sec = self.max_time_inside_sphere

                goal_handle.publish_feedback(feedback_msg)

                drone_is_in_sphere = self.is_drone_in_sphere(self.curr_state, goal_handle, 0.8) 

            # The value 0.08 is in meters used for as error range in Whycon coordinates for LQR controller. If you are using PID controller, it will become 0.8 as PID Whycon coordinates are in decimeters.

                if not drone_is_in_sphere and self.point_in_sphere_start_time is None:
                    pass
            
                elif drone_is_in_sphere and self.point_in_sphere_start_time is None:
                    self.point_in_sphere_start_time = self.dtime
                    self.get_logger().info('Drone in sphere for 1st time')#you can choose to comment this out to get a better look at other logs

                elif drone_is_in_sphere and self.point_in_sphere_start_time is not None:
                    self.time_inside_sphere = self.dtime- self.point_in_sphere_start_time
                    self.get_logger().info('Drone in sphere')#you can choose to comment this out to get a better look at other logs
                              
                elif not drone_is_in_sphere and self.point_in_sphere_start_time is not None:
                    self.get_logger().info('Drone out of sphere')#you can choose to comment this out to get a better look at other logs
                    self.point_in_sphere_start_time = None
                    self.time_inside_sphere = 0
                    self.max_time_inside_sphere = 0

                if self.time_inside_sphere > self.max_time_inside_sphere:
                    self.max_time_inside_sphere = self.time_inside_sphere

                if self.max_time_inside_sphere >= 2:
                    break
        else:
            while True:
                feedback_msg.current_waypoint.pose.position.x = round(self.curr_state[0],2)
                feedback_msg.current_waypoint.pose.position.y = round(self.curr_state[1],2)
                feedback_msg.current_waypoint.pose.position.z = round(self.curr_state[2],2)
                feedback_msg.current_waypoint.header.stamp.sec = 1

                goal_handle.publish_feedback(feedback_msg)

                drone_is_in_sphere = self.is_drone_in_sphere(self.curr_state, goal_handle, 0.8) 

                if drone_is_in_sphere:  
                    break

        goal_handle.succeed()

        #create a NavToWaypoint result object. Refer to Writing an action server and client (Python) in ROS 2 tutorials
        result = NavToWaypoint.Result()
        result.hov_time = self.dtime - self.duration #this is the total time taken by the drone in trying to stabilize at a point
        return result

    def is_drone_in_sphere(self, drone_pos, sphere_center, radius):
        '''
Purpose:
---
Checks if the drone's current position is within a specified radius of the target waypoint.

Input Arguments:
---
`drone_pos` : [list of float]
    List containing current drone x, y, z position.

`sphere_center` : [ServerGoalHandle]
    Action server goal handle containing waypoint position.

`radius` : [float]
    Radius of sphere.

Returns:
---
[out] : [bool]
    True if drone is within sphere, False otherwise.

Example call:
---
self.is_drone_in_sphere(drone_pos, sphere_center, radius)
'''

        return (
            (drone_pos[0] - sphere_center.request.waypoint.position.x)** 2
            + (drone_pos[1] - sphere_center.request.waypoint.position.y) ** 2
            + (drone_pos[2] - sphere_center.request.waypoint.position.z) ** 2
        ) < radius**2


def main(args=None):
    '''
Purpose:
---
Initializes ROS2, starts the waypoint server node using a multi-threaded executor,
and keeps the node spinning until shutdown.

Input Arguments:
---
`args` : [list or None]
    Optional command line arguments for rclpy.init()

Returns:
---
None

Example call:
---
main()
'''

    rclpy.init(args=args)

    waypoint_server = WayPointServer()
    executor = MultiThreadedExecutor()
    executor.add_node(waypoint_server)
    
    try:
         executor.spin()
    except KeyboardInterrupt:
        waypoint_server.get_logger().info('KeyboardInterrupt, shutting down.\n')
    finally:
         waypoint_server.destroy_node()
         rclpy.shutdown()


if __name__ == '__main__':
    main()
