#!/usr/bin/env python3

# This python file runs a ROS 2-node of name waypoint_server which implements an action server to navigate the Swift Pico Drone to the given waypoints.
# You can use either PID or LQR controller to navigate the drone to the given waypoints.


import time
import math
from tf_transformations import euler_from_quaternion

import rclpy
from rclpy.action import ActionServer
from rclpy.node import Node
from rclpy.callback_groups import ReentrantCallbackGroup
from rclpy.executors import MultiThreadedExecutor
from rclpy.action.server import ServerGoalHandle
import numpy as np
#import control specific libraries
#import the action
from waypoint_navigation.action import NavToWaypoint
#pico control specific libraries
from swift_msgs.msg import SwiftMsgs
from geometry_msgs.msg import PoseArray
from error_msg.msg import Error
from controller_msg.msg import PIDTune
from nav_msgs.msg import Odometry

class WayPointServer(Node):

    def __init__(self):
        super().__init__('waypoint_server')

        self.pid_or_lqr_callback_group = ReentrantCallbackGroup()
        self.action_callback_group = ReentrantCallbackGroup()
        self.odometry_callback_group = ReentrantCallbackGroup()

        self.time_inside_sphere = 0
        self.max_time_inside_sphere = 0
        self.point_in_sphere_start_time = None
        self.duration = 0


        self.yaw = 0.0
        self.xyz = [0.0, 0.0, 0.0, 0.0]
        self.curr_state = [0.0, 0.0, 0.0]
        self.desired_state = [0.0, 0.0, 0.0]
        self.dtime = 0

        # Declaring a cmd of message type swift_msgs and initializing values
        self.cmd = SwiftMsgs()
        self.cmd.rc_roll = 1500
        self.cmd.rc_pitch = 1500
        self.cmd.rc_yaw = 1500
        self.cmd.rc_throttle = 1500

        self.Kp = [-10.0, -20.0, 24.0]
        self.Ki = [0.08, 0.08, 0.08]
        self.Kd = [-5.0, -12.0, 12.0]

        #Initiate or declare other variables here depending upon whether you are implementing PID or LQR controller.
        self.prev_error = [0.0, 0.0, 0.0]
        self.max_values = [2000, 2000, 2000]
        self.min_values = [1000, 1000, 1000]
        self.error = [0.0, 0.0, 0.0]
        self.p_term = [0.0, 0.0, 0.0]
        self.d_term = [0.0, 0.0, 0.0]
        self.i_term = [0.0, 0.0, 0.0]
        self.PID_out = [0.0, 0.0, 0.0]
        self.dt = [0.0, 0.0, 0.0]
        self.error_sum = [0.0, 0.0, 0.0]
        self.filterted_curr_state = [0.0, 0.0, 0.0]
        self.alpha = 0.2
        self.single_sec_points = [
            [-7.64, 3.06, 30.22],#wp1
            [-8.22, 6.02, 30.22],#wp2
            [-9.11, 9.27, 31.27],#start
            [-5.976, 8.810, 31.27],#wp3
            [-3.26, 8.41, 29.88],#hula_hoop_2_entry:
            [0.87, 8.18, 29.05],#hula_hoop_2_exit:
            [3.929, 7.347, 29.05],#wp4
            [6.60, 6.62, 30.20],#block_1:
            [6.7375, 3.3200, 30.6450],#wp5
            [6.8750, -0.1900, 30.0900],#wp6
            [7.0125, -3.5950, 31.5350],#wp7
            [7.15, -7.00, 31.98],#block_2:
            [4.0, -7.62, 30.59],#wp8:
            [0.8, -8.04, 29.20],#hula_hoop_1_exit:
            [-3.26, -8.12, 29.48],#hula_hoop_1_entry:
            [-5.94, -8.36, 29.54],#wp9:
            [-7.82, -5.55, 30.22],#wp10
            [-7.49, -2.83, 30.22],#wp11
            [-6.9, 0.09, 32.16]#destination:
        ]
        self.sec2_points = [
            [9.13, 8.80, 30.40],#P1C(application)
            [4.43, -4.30, 31.1],#P2A(application)
        ]
        self.critical_points = [
            [-7.0, 0.0, 30.22],#hover:
            [-9.11, 9.27, 31.27],#destination:
            [-9.07, 9.23, 32.57],#pickup:
            [8.62, 8.80, 28.69],#P1C(plant)
            [4.43, -4.30, 29.74],#P2A(plant)
        ]


        self.sample_time = 0.01 #put the appropriate value according to your controller

        self.command_pub = self.create_publisher(SwiftMsgs, '/drone_command', 10)
        self.pos_error_pub = self.create_publisher(Error, '/position_error', 10)

        
        self.create_subscription(PoseArray, '/whycon/poses', self.whycon_callback, 1)
        #Add other sunscribers here
        self.create_subscription(PIDTune, "/throttle_pid", self.altitude_set_pid, 1)
        self.create_subscription(PIDTune, "/pitch_pid", self.pitch_set_pid, 1)
        self.create_subscription(PIDTune, "/roll_pid", self.roll_set_pid, 1)
        self.create_subscription(Odometry, '/rotors/odometry', self.odometry_callback, 10, callback_group=self.odometry_callback_group)

        #create an action server for the action 'NavToWaypoint'. Refer to Writing an action server and client (Python) in ROS 2 tutorials
        #action name should 'waypoint_navigation'.
        #include the action_callback_group in the action server. Refer to executors in ROS 2 concepts
        self.pico_server_ = ActionServer(
            self,
            NavToWaypoint,
            "waypoint_navigation",
            execute_callback=self.execute_callback,
            callback_group=self.action_callback_group)
        self.get_logger().info("Action server has been started.")
        
        self.arm()
        #define the function to be run inside the timer callback. This function will implement the PID or LQR algorithm
        self.timer = self.create_timer(self.sample_time, self.pid, callback_group=self.pid_or_lqr_callback_group)

    def disarm(self):
        self.cmd.rc_roll = 1000
        self.cmd.rc_yaw = 1000
        self.cmd.rc_pitch = 1000
        self.cmd.rc_throttle = 1000
        self.cmd.rc_aux4 = 1000
        self.command_pub.publish(self.cmd)


    def arm(self):
        self.disarm()
        self.cmd.rc_roll = 1500
        self.cmd.rc_yaw = 1500
        self.cmd.rc_pitch = 1500
        self.cmd.rc_throttle = 1500
        self.cmd.rc_aux4 = 2000
        self.command_pub.publish(self.cmd)


	# Whycon callback function
	# The function gets executed each time when /whycon node publishes /whycon/poses 
    def whycon_callback(self, msg):

        if not msg.poses or len(msg.poses) == 0:
            self.get_logger().warn("No poses received")
            return

        else:
            #complete the function according to your controller as you did in task 1c.
            raw_x = msg.poses[0].position.x 
            raw_y = msg.poses[0].position.y 
            raw_z = msg.poses[0].position.z 

            self.filterted_curr_state[0]=self.alpha * raw_x + (1 - self.alpha)* self.filterted_curr_state[0]
            self.filterted_curr_state[1]=self.alpha * raw_y + (1 - self.alpha)* self.filterted_curr_state[1]
            self.filterted_curr_state[2]=self.alpha * raw_z + (1 - self.alpha)* self.filterted_curr_state[2]

            self.curr_state[0] = self.filterted_curr_state[0]
            self.curr_state[1] = self.filterted_curr_state[1]
            self.curr_state[2] = self.filterted_curr_state[2]

        self.dtime = msg.header.stamp.sec

    # If you are using PID controller, then define callback function like altitide_set_pid to tune pitch, roll.
    #If you are using LQR controller, then define a functions which were given in the boiler plate code of task 1c and the ones which you have defined on yur own.
    def altitude_set_pid(self, alt):
        self.Kp[2] = alt.kp * 0.03  # This is just for an example. You can change the ratio/fraction value accordingly
        self.Ki[2] = alt.ki * 0.008
        self.Kd[2] = alt.kd * 0.6

    def pitch_set_pid(self, alt):
        self.Kp[0] = alt.kp * 0.03  # This is just for an example. You can change the ratio/fraction value accordingly
        self.Ki[0] = alt.ki * 0.008
        self.Kd[0] = alt.kd * 0.6

    def roll_set_pid(self, alt):
        self.Kp[1] = alt.kp * 0.03  # This is just for an example. You can change the ratio/fraction value accordingly
        self.Ki[1] = alt.ki * 0.008
        self.Kd[1] = alt.kd * 0.6

    def odometry_callback(self, msg):
        orientation_q = msg.pose.pose.orientation
        orientation_list = [orientation_q.x, orientation_q.y, orientation_q.z, orientation_q.w]
        roll, pitch, yaw = euler_from_quaternion(orientation_list)

        self.roll_deg = math.degrees(roll)
        self.pitch_deg = math.degrees(pitch)
        self.yaw_deg = math.degrees(yaw)
        self.yaw = self.yaw_deg		

    #define the function to be run inside the timer callback. This function will implement the PID or LQR algorithm. 
    # This will be either 'pid' finction or 'controller' function as you can see in the boiler plate for PID or LQR for task 1c.
    def pid(self):
        self.error[0] = self.curr_state[0] - self.desired_state[0]
        self.error[1] = self.curr_state[1] - self.desired_state[1]
        self.error[2] = self.curr_state[2] - self.desired_state[2]

        for i in range(3):
            self.p_term[i] = self.Kp[i] * self.error[i] 
            
            self.dt[i] = (self.error[i] - self.prev_error[i]) / self.sample_time
            self.d_term[i] = self.Kd[i] * self.dt[i]

            self.error_sum[i] += self.error[i] * self.sample_time
            self.i_term[i] = self.error_sum[i] * self.Ki[i]

            self.PID_out[i] = self.p_term[i]+self.i_term[i]+self.d_term[i] 
        
        self.out_roll = self.PID_out[1]
        self.out_pitch = self.PID_out[0]
        self.out_throttle = self.PID_out[2]

        self.cmd.rc_roll = 1500 + int(self.out_roll)
        self.cmd.rc_pitch = 1500 + int(self.out_pitch)
        self.cmd.rc_throttle = 1500 + int(self.out_throttle)

        self.cmd.rc_roll = max(self.min_values[1],min(self.cmd.rc_roll,self.max_values[1]))
        self.cmd.rc_pitch = max(self.min_values[0],min(self.cmd.rc_pitch,self.max_values[0]))
        self.cmd.rc_throttle = max(self.min_values[2],min(self.cmd.rc_throttle,self.max_values[2]))

        for i in range(3):
            self.prev_error[i] = self.error[i]

        #publishing the error
        self.command_pub.publish(self.cmd)
        msg = Error()
        msg.roll_error = self.error[1]    
        msg.pitch_error = self.error[0] 
        msg.throttle_error = self.error[2]  
        self.pos_error_pub.publish(msg)

    def execute_callback(self, goal_handle:ServerGoalHandle):

        self.get_logger().info('Executing goal...')
        self.desired_state[0] = goal_handle.request.waypoint.position.x
        self.desired_state[1] = goal_handle.request.waypoint.position.y
        self.desired_state[2] = goal_handle.request.waypoint.position.z

        self.get_logger().info(f'New Waypoint Set: {self.desired_state}')
        self.max_time_inside_sphere = 0
        self.point_in_sphere_start_time = None
        self.time_inside_sphere = 0
        self.duration = self.dtime

        current_waypoint = [
            self.desired_state[0],
            self.desired_state[1],
            self.desired_state[2]
            ]
        STABILIZATION_LIMIT = 3.0
        def is_in_list(target_point, point_list):
            return any(np.isclose(target_point, p, atol=0.01).all() for p in point_list)
        
        if is_in_list(current_waypoint, self.sec2_points):
            STABILIZATION_LIMIT = 2.0
        elif is_in_list(current_waypoint, self.single_sec_points):
            STABILIZATION_LIMIT = 1.0
        elif is_in_list(current_waypoint, self.critical_points):
            STABILIZATION_LIMIT = 3.0
        else:
            STABILIZATION_LIMIT = 3.0

        self.get_logger().info(f'Waypoint set: {current_waypoint}. Required Hold: {STABILIZATION_LIMIT}s')

        #create a NavToWaypoint feedback object. Refer to Writing an action server and client (Python) in ROS 2 tutorials.
        feedback_msg = NavToWaypoint.Feedback()
        #--------The script given below checks whether you are hovering at each of the waypoints(goals) for max of 3s---------#
        # This will help you to analyse the drone behaviour and help you to tune the PID better.

        while True:
			#current whycon poses
            feedback_msg.current_waypoint.pose.position.x = self.curr_state[0]
            feedback_msg.current_waypoint.pose.position.y = self.curr_state[1]
            feedback_msg.current_waypoint.pose.position.z = self.curr_state[2]
            feedback_msg.current_waypoint.header.stamp.sec = self.max_time_inside_sphere

            goal_handle.publish_feedback(feedback_msg)

            drone_is_in_sphere = self.is_drone_in_sphere(self.curr_state, goal_handle, 0.8) 

            # The value 0.08 is in meters used for as error range in Whycon coordinates for LQR controller. If you are using PID controller, it will become 0.8 as PID Whycon coordinates are in decimeters.

            if not drone_is_in_sphere and self.point_in_sphere_start_time is None:
                pass
            
            elif drone_is_in_sphere and self.point_in_sphere_start_time is None:
                self.point_in_sphere_start_time = self.dtime
                self.get_logger().info('Drone in sphere for 1st time')#you can choose to comment this out to get a better look at other logs

            elif drone_is_in_sphere and self.point_in_sphere_start_time is not None:
                self.time_inside_sphere = self.dtime - self.point_in_sphere_start_time
                self.get_logger().info('Drone in sphere')#you can choose to comment this out to get a better look at other logs
                             
            elif not drone_is_in_sphere and self.point_in_sphere_start_time is not None:
                self.get_logger().info('Drone out of sphere')#you can choose to comment this out to get a better look at other logs
                self.point_in_sphere_start_time = None

            if self.time_inside_sphere > self.max_time_inside_sphere:
                self.max_time_inside_sphere = self.time_inside_sphere

            if self.max_time_inside_sphere >= STABILIZATION_LIMIT:
                break
            

        goal_handle.succeed()

        #create a NavToWaypoint result object. Refer to Writing an action server and client (Python) in ROS 2 tutorials
        result = NavToWaypoint.Result()
        result.hov_time = self.dtime - self.duration #this is the total time taken by the drone in trying to stabilize at a point
        return result

    def is_drone_in_sphere(self, drone_pos, sphere_center, radius):
        return (
            (drone_pos[0] - sphere_center.request.waypoint.position.x) ** 2
            + (drone_pos[1] - sphere_center.request.waypoint.position.y) ** 2
            + (drone_pos[2] - sphere_center.request.waypoint.position.z) ** 2
        ) <= radius**2


def main(args=None):
    rclpy.init(args=args)

    waypoint_server = WayPointServer()
    executor = MultiThreadedExecutor()
    executor.add_node(waypoint_server)
    
    try:
         executor.spin()
    except KeyboardInterrupt:
        waypoint_server.get_logger().info('KeyboardInterrupt, shutting down.\n')
    finally:
         waypoint_server.destroy_node()
         rclpy.shutdown()


if __name__ == '__main__':
    main()
