#!/usr/bin/env python3
'''
# Team ID:          <  eYRC#1710  >
# Theme:            < Krishi Drone  >
# Author List:      < Ameya Degaonkar,Sarthak Benodkar,Aditya Dengale,Pranav Rokade >
# Filename:         < pico_client>
# Functions:        < __init__, send_goal, goal_response_callback, get_result_callback, 
# feedback_callback, send_request, receive_goals, main >
# Global variables: < None >
'''


import time
import rclpy
from rclpy.action import ActionClient
from rclpy.node import Node
from rclpy.action.client import ClientGoalHandle
#import the action and service
from waypoint_navigation.action import NavToWaypoint
from waypoint_navigation.srv import GetWaypoints


class WayPointClient(Node):

    def __init__(self):
        '''
Purpose:
---
Initializes the waypoint client node, sets up action and service 
clients to interact with the waypoint server,
and prepares for sending and receiving waypoint navigation goals.

Input Arguments:
---
`self` : [WayPointClient]
Instance reference for the node itself.

Returns:
---
None

Example call:
---
client = WayPointClient()
'''

        super().__init__('waypoint_client')
        self.goals = []
        self.goal_index = 0
        #create an action client for the action 'NavToWaypoint'. Refer to Writing an action server and client (Python) in ROS 2 tutorials
        #action name should 'waypoint_navigation'.
        self.action_client = ActionClient(self,NavToWaypoint,"waypoint_navigation")
        
        #create a client for the service 'GetWaypoints'. Refer to Writing a simple service and client (Python) in ROS 2 tutorials
        #service name should be 'waypoints'
        self.cli = self.create_client(GetWaypoints,'waypoints')

        while not self.cli.wait_for_service(timeout_sec=1.0):
            self.get_logger().info('service not available, waiting again...')

        #create a request object for GetWaypoints service.
        self.req = GetWaypoints.Request()

    
    ###action client functions

    def send_goal(self, waypoint):
        '''
Purpose:
---
Sends the current waypoint as a goal to the action server for drone navigation.

Input Arguments:
---
`waypoint` : [list]
List containing [x, y, z] coordinates of the waypoint.

Returns:
---
None

Example call:
---
self.send_goal([x, y, z])
'''


        #create a NavToWaypoint goal object.
        goal_msg = NavToWaypoint.Goal()

        goal_msg.waypoint.position.x = waypoint[0]
        goal_msg.waypoint.position.y = waypoint[1]
        goal_msg.waypoint.position.z = waypoint[2]

        #create a method waits for the action server to be available.
        self.action_client.wait_for_server()

        self.send_goal_future = self.action_client.send_goal_async(goal_msg, feedback_callback=self.feedback_callback)    
        self.send_goal_future.add_done_callback(self.goal_response_callback)

    def goal_response_callback(self, future):
        '''
Purpose:
---
Handles the response from the action server indicating if the goal was accepted.

Input Arguments:
---
`future` : [Future]
Future object containing the result of the goal request.

Returns:
---
None

Example call:
---
self.goal_response_callback(future)
'''


        #complete the goal_response_callback. Refer to Writing an action server and client (Python) in ROS 2 tutorials
        self.goal_handle_ = future.result() 
        if self.goal_handle_.accepted:
            self.goal_handle_.get_result_async().add_done_callback(self.get_result_callback)
        

    def get_result_callback(self, future):
        '''
Purpose:
---
Receives the result from the action server and proceeds to the next waypoint if any remain.

Input Arguments:
---
`future` : [Future]
Future object containing the result of the navigation goal.

Returns:
---
None

Example call:
---
self.get_result_callback(future)
'''


        #complete the missing line
        result = future.result().result
        self.get_logger().info('Result: {0}'.format(result.hov_time))

        self.goal_index += 1

        if self.goal_index < len(self.goals):
            self.send_goal(self.goals[self.goal_index])
        else:
            self.get_logger().info('All waypoints have been reached successfully')      

    def feedback_callback(self, feedback_msg):
        '''
Purpose:
---
Processes feedback from the action server, including real-time drone position and timer data.

Input Arguments:
---
`feedback_msg` : [FeedbackMessage]
Message containing feedback data from the action server.

Returns:
---
None

Example call:
---
 self.feedback_callback(feedback_msg)
 '''


        #complete the missing line
        feedback = feedback_msg.feedback
        x = feedback.current_waypoint.pose.position.x
        y = feedback.current_waypoint.pose.position.y
        z = feedback.current_waypoint.pose.position.z
        t = feedback.current_waypoint.header.stamp.sec
        self.get_logger().info(f'Received feedback! The current whycon position is: {x}, {y}, {z}')
        self.get_logger().info(f'Max time inside sphere: {t}')


    #service client functions

    def send_request(self):
        '''
Purpose:
---
Sends a request to the waypoint service for a list of waypoints.

Input Arguments:
---
None

Returns:
---
`future` : [Future]
Future containing the service response.

Example call:
---
future = self.send_request()
'''

        #  complete send_request method, which will send the request and return a future
        self.req.get_waypoints = True 
        future = self.cli.call_async(self.req)
        return future 

    def receive_goals(self):
        '''
Purpose:
---
Requests waypoints from service, loads them into goals list, and starts navigation.

Input Arguments:
---
None

Returns:
---
None

Example call:
---
self.receive_goals()
'''

        future = self.send_request()
        #write a statement to execute the service until the future is complete
        rclpy.spin_until_future_complete(self,future)

        if future.result() is None:
            self.get_logger().error('Failed to get waypoints from service')
            return

        response = future.result()
        self.get_logger().info('Waypoints received by the action client')

        for pose in response.waypoints.poses:
            waypoints = [pose.position.x, pose.position.y, pose.position.z]
            self.goals.append(waypoints)
            self.get_logger().info(f'Waypoints: {waypoints}')

        self.send_goal(self.goals[0])
    

def main(args=None):
    '''
Purpose:
---
Initializes the ROS2 environment and runs the WayPointClient node.

Input Arguments:
---
`args` : [list, optional]
Command line arguments passed to rclpy.init()

Returns:
---
None

Example call:
---
main()
'''

    rclpy.init(args=args)

    waypoint_client = WayPointClient()
    waypoint_client.receive_goals()

    try:
        rclpy.spin(waypoint_client)
    except KeyboardInterrupt:
        waypoint_client.get_logger().info('KeyboardInterrupt, shutting down.\n')
    finally:
        waypoint_client.destroy_node()
        rclpy.shutdown()
    
    rclpy.shutdown()


if __name__ == '__main__':
    main()
        
