#!/usr/bin/env python3
'''
# Team ID:          <  eYRC#1710 >
# Theme:            < Krishi Drone >
# Author List:      < Ameya Degaonkar,Sarthak Benodkar,Aditya Dengale,Pranav Rokade>
# Filename:         < waypoint_service >
# Functions:        < __init__,waypoint_callback,waypoint_callback,main >
# Global variables: < none >
'''

import rclpy
from rclpy.node import Node
from geometry_msgs.msg import Pose
from waypoint_navigation.srv import GetWaypoints

class WayPoints(Node):

    def __init__(self):
        '''
Purpose:
---
< starts the waypoint_serice node. Sets up a ROS2 service to provide list of waypoint coordinates
pico_client.py >

Input Arguments:
---
None


Returns:
---
None

Example call:
---
< called automatically when an instance of the waypoint_service class is created 
waypoint_service = WaypointServiceNode() >
'''

        super().__init__('waypoints_service')
        self.srv = self.create_service(GetWaypoints, 'waypoints', self.waypoint_callback)
        self.waypoints = [
            [-7.00, 0.00, 29.22],#hover:
            [-7.64, 3.06, 29.22],#wp1:
            [-8.22, 6.02, 29.22],#wp2:
            [-9.11, 9.27, 29.27],#wp3:
            [-5.98, 8.81, 29.27],#wp4:
            [-3.26, 8.41, 29.88],#wp5:
            [0.87, 8.18, 29.05],#wp6:
            [3.93, 7.35, 29.05]#wp7:
        ]

    
    def waypoint_callback(self, request, response):
        
        '''
Purpose:
---
< Handles incoming service requests for waypoint coordinates from clients,if request is valid updates
the respose with full list of waypoints>

Input Arguments:
---
`request` :  [GetWaypoints.Request]
        The service request object containing a boolean flag to trigger waypoint retrieval.

    `response` :  [GetWaypoints.Response]
        The service response object to be populated with waypoint data for the client.

Returns:
---
 `response` :  [GetWaypoints.Response]
        The populated response object containing an array of waypoint poses if the request is accepted.

Example call:
---
 # Automatically called by ROS2 service server when a client requests waypoints:
    # response = waypoint_callback(request, response)
'''

        if request.get_waypoints == True :
            response.waypoints.poses = [Pose() for _ in range(len(self.waypoints))]
            for i in range(len(self.waypoints)):
                response.waypoints.poses[i].position.x = self.waypoints[i][0]
                response.waypoints.poses[i].position.y = self.waypoints[i][1]
                response.waypoints.poses[i].position.z = self.waypoints[i][2]
            self.get_logger().info("Incoming request for Waypoints")
            return response

        else:
            self.get_logger().info("Request rejected")

def main():
    '''
    Purpose:
    ---
    Initializes the ROS 2 Python environment and starts the waypoint service node.
    Spins the node so it remains active, listening for requests until shutdown is requested.

    Input Arguments:
    ---
    None

    Returns:
    ---
    None

    Example call:
    ---
    # Called implicitly when the script is executed as a standalone file:
    # if __name__ == '__main__':
    #     main()
    '''

    rclpy.init()
    waypoints = WayPoints()

    try:
        rclpy.spin(waypoints)
    except KeyboardInterrupt:
        waypoints.get_logger().info('KeyboardInterrupt, shutting down.\n')
    finally:
        waypoints.destroy_node()
        rclpy.shutdown()

if __name__ == '__main__':
    main()
        
